/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF("/mesh.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pMesh1.geometry}
        material={nodes.pMesh1.material}
      />
    </group>
  );
}

useGLTF.preload('/mesh.gltf')
